### ISSUE TITLE
How to generate dynamic text masks?

### ISSUE THREAD

**Issue by AkarinVS** [Beatrice-Raws/encode-scripts#3]
Hello,

I've learned a lot from the published scripts, thanks!

I'm wondering how did you generate dynamic text masks like the one here:
https://github.com/Beatrice-Raws/encode-scripts/blob/master/Hyouka/title%2001%20mask.mp4

Any hints will be appreciated. Thanks again for making your script open source.

/cc @Endilll

**Comment by DJATOM** [comment]
Endill made them in Adobe After Effects. Probably there are some tutorials on YouTube, maybe he will post some info.

**Comment by Endilll** [comment]
I forgot to push AE project to Hyouka sources. Now that's fixed in 0ca3cde1fa89c9e2006880d0cb6ce43f3a480ebe
Clips it's referencing are too big to upload, so I can share a sample in private if you'd like. But even without it project should be quite useful for you.

If I had to highlight some features of AE to do masking, that'd be Auto-trace.

But Hyouka masks were quite boring and could be done in Aegisub instead, given some perseverance. 
If you'd like to see true power of AE in action, see GITS SAC OP mask. That was the most interesting mask I've done so far.

For all my love towards open-source and Aegisub in particular, there were no turning back after I discovered AE and it'd animation and 3D facilities.

Feel free to reach out to me on our Discord server. I can probably even do some training for you if you're interested
